project:
  type: book
  output-dir: docs

lang: kr

book:
  title: "데이터 문해력과 디지털 글쓰기"
  subtitle: "오픈소스 소프트웨어: 빛에듀(Bit-Eud)"
  author: "이광춘 / 한국 R 사용자회"
  date: last-modified
  chapters:
    - index.qmd
    - part: "디지털 글쓰기"
      chapters:
        - intro.qmd
    - part: "빛에듀(Bit-Edu)"
      chapters:
        - summary.qmd
    - references.qmd
  sidebar:
    pinned: true
    
  repo-url: https://github.com/bit2r/bitBook
  search: 
    location: sidebar
    type: textbox
  downloads: [pdf]

bibliography: references.bib
link-citations: yes
csl: apa-single-spaced.csl
mainfont: "NanumMyeongjo"
sansfont: "NanumGothic"
monofont: "D2Coding"

format:
  html:
    theme: cosmo
    cover-image: koRea_logo.png
  pdf:
    documentclass: scrreprt



