project:
  type: book
  output-dir: docs

lang: kr

book:
  title: "데이터 문해력과 디지털 글쓰기"
  subtitle: "오픈소스 소프트웨어: 빛에듀(Bit-Edu)"
  author: "한국 R 사용자회"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
  chapters:
    - index.qmd
    - part: "글쓰기"
      chapters:
        - part_I_01_intro.qmd
        - part_I_02_history.qmd
    - part: "디지털 글쓰기"
      chapters:
        - markdown_01_mess.qmd
        - markdown_02_markdown.qmd
        - markdown_03_advanced.qmd
        - part_II_01_fonts.qmd
        - part_II_02_pdf.qmd
    - part: "빛에듀(Bit-Edu)"
    - part: "통계패키지(BitStat)"
      chapters:
        - BitStat_00_install.qmd
        - BitStat_01_data_prepare.qmd
        - BitStat_02_descriptive_summary.qmd
        - BitStat_03_correlation.qmd
    - references.qmd
  sidebar:
    pinned: true
    
  repo-url: https://github.com/bit2r/bitBook
  search: 
    location: sidebar
    type: textbox
  downloads: [pdf]

bibliography: bibliography.bib
link-citations: yes
mainfont: "NanumMyeongjo"
sansfont: "NanumGothic"
monofont: "D2Coding"

format:
  html:
    theme: cosmo
    cover-image: koRea_logo.png
  pdf:
    documentclass: scrreprt
    papersize: b5paper
    geometry: margin=2cm
    header-includes:
      - \usepackage{lastpage}
      - \usepackage{fancyhdr}
      - \definecolor{col1}{RGB}{5, 53, 255}
      - \fancypagestyle{ttlpage}{\fancyfoot[C]{{\thepage} of \pageref{LastPage}}}
      - \thispagestyle{ttlpage}
      - \pagestyle{fancy}
      - \fancyhead[EL,OL]{\rightmark}
      - \fancyhead[EC,OC]{}
      - \fancyhead[ER,OR]{빛에듀(Bit-Edu)}
      - \fancyfoot[EL,OL]{\color{col1}{한국R사용자회}}
      - \fancyfoot[EC,OC]{\textbf{데이터 문해력과 디지털 글쓰기}}
      - \fancyfoot[ER,OR] {총 \pageref{LastPage} 중 {\thepage}}

# quarto.cmd render --to pdf -s -V papersize:b5 --output-dir _pdf_B5


