# 서문 {.unnumbered}

사단법인 한국 알(R) 사용자회는 디지털 불평등 해소와 통계 대중화를 위해 
2022년 설립되었습니다. 오픈 통계 패키지(BitStat) 개발을 비롯하여
최근에 데이터 사이언스 관련 교재도 함께 제작하여 발간하는 작업을 수행하고 있습니다.

커뮤니티 활동으로 [서울 R 미트업](https://www.meetup.com/seoul-r-meetup/)을 매월 텍스트 마이닝, 재무회계, Shiny 앱개발, 바이오 헬스케어 등 주제를 달리하여 개최하고 있습니다. 2017년부터 시작된 서울 R 미트업 발표자료는 [저장소](https://tidyverse-korea.github.io/seoul-R/)에서 확인할 수 있습니다.

다음은 한국 R 사용자회에서 공공에 오픈한 전자책 콘텐츠입니다.

그 첫번째 결과물로 John Fox 교수님이 개발한 설치형 오픈 통계 패키지 `Rcmdr`[@fox2016using] [@rcmdr2022manual] [@rcmdr2005paper] 를 신종화 님께서 한글화 및 문서화에 10년 넘게 기여해주신 한국알사용자회 저작권을 흔쾌히 허락해 주셔서 [설치형 오픈 통계 패키지 - `Rcmdr`](https://r2bit.com/Rcmdr/)로 세상에 나왔습니다.

두번째 활동을 여기저기 산재되어 있던 시각화 관련 자료를 묶어
**[데이터 시각화(Data Visualization)](https://r2bit.com/book_viz/)**를 전자책 형태로 공개하였고, 데이터 분석 관련 저술을 이어 진행하게 되었습니다.

세번째 활동으로 데이터 사이언스가 하나로 구성되지 않은 것을 간파하고
데이터 사이언스를 지탱하는 기본기술을 5가지로 정리한 
**[데이터 과학을 지탱하는 기본기](https://r2bit.com/book_analytics/)** 전자책을 
공개했습니다.

네번째 활동으로 "데이터 과학 프로그래밍" 저작을 위해 ["Python for Everybody"](https://www.py4e.com/book)와 
[Python for Informatics: Exploring Information](http://www.py4inf.com/)에 기반하여
2015년부터 시작된 [모두를 위한 파이썬](http://aispiration.com/pythonlearn-kr/) 한글화
프로젝트를 추진했습니다. [데이터 과학 프로그래밍](https://r2bit.com/book_programming/) 웹사이트에서 프로그래밍 교재를 확인할 수 있다.


그외, 데이터 분석 언어 R에 관한 지식을 신속히 습득하여 독자들이 갖고 있는 문제에 
접목시키고자 하시는 분은 한국 알(R) 사용자회에서 번역하여 공개한 
[R 신병훈련소(Bootcamp)](https://r2bit.shinyapps.io/rbootcamp/) 과정을
추천드립니다.

"데이터 사이언스 프로그래밍" 저작물을 비롯한 한국 알(R) 사용자회 저작물은 크리에이티브 커먼즈 [저작자표시-비영리-동일조건 변경 허락 (BY-NC-SA)](http://ccl.cckorea.org/about/)
라이선스를 준용하고 있습니다. 
